language: go
env:
  global:
    - GO111MODULE=on

matrix:
  include:
    - go: 1.11.x
      env: DEPLOY_BUILD=true
    - go: tip

before_install:
  - go get -u golang.org/x/tools/cmd/goimports

install:
  - go mod download

script:
  - diff <(goimports -d *.go cmd/gocloc/main.go examples/*) <(printf "")
  - go test -v ./

deploy:
  - provider: script
    skip_cleanup: true
    script: curl -sL https://git.io/goreleaser | bash
    on:
      condition: $DEPLOY_BUILD = true
      tags: true
